version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_HOST_URL=http://localhost:3001
      - NEXT_PUBLIC_GRAPHQL_URL=http://backend:3000/graphql
    depends_on:
      - backend